name: Ruby

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / MongoDB ${{ matrix.mongodb }} / Mongoid ${{ matrix.mongoid }}
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/mongoid${{ matrix.mongoid }}.gemfile
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.0.6'
          - '3.1.4'
          - '3.2.2'
        mongoid:
          - 7
        mongodb:
          - '4.0'
          - '4.2'
          - '4.4'
    steps:
    - uses: actions/checkout@v3
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb }}
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
